modLoader="javafml"
loaderVersion="[36,)"

license="GNU Lesser General Public License v3.0"
issueTrackerURL="https://github.com/LiskoSlayer63/immersiveextras/issues"

[[mods]]
modId="immersiveextras"
version="1.0.1"

displayName="Immersive Extras"
displayURL="https://www.curseforge.com/minecraft/mc-mods/immersiveextras"
#logoFile="garbagebins.png"
authors="LiskoSlayer63"

description='''
Adds some extra technology
'''

[[dependencies.immersiveextras]]
	modId="immersiveengineering"
	mandatory=true
	versionRange="[1.16.5-5.0.4-139,)"
	ordering="BEFORE"
	side="BOTH"

[[dependencies.immersiveextras]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.immersiveextras]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
	